/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ControladorFilmes;
import Controle.ControladorUsuarios;
import Modelo.TipoUsuario;
import Modelo.Usuario;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author jw
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal(ControladorUsuarios controlador, Usuario u, ControladorFilmes controlador2) {
        this.controladorU=controlador;
        this.controladorF=controlador2;
        this.u=u;
        initComponents();
        jLabelBemvindo.setText("Bem-vindo(a) "+u.getNome());
         switch (u.getTipoUsuario()){
                case ATENDENTE:
                    jButtonCadastrarFuncionario.setVisible(false);
                    jButtonListarFuncionarios.setVisible(false);
                    break;
                case GERENTE:
                    jButtonCadastrarFuncionario.setVisible(true);
                    jButtonListarFuncionarios.setVisible(true);
                    break;
                default:
                    new realizaEmprestimo(controladorF, u).setVisible(true);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBemvindo = new javax.swing.JLabel();
        jButtonCFilme = new javax.swing.JButton();
        jButtonListarFilmes = new javax.swing.JButton();
        jButtonCadastrarCliente = new javax.swing.JButton();
        jButtonListarCLiente = new javax.swing.JButton();
        jButtonCadastrarFuncionario = new javax.swing.JButton();
        jButtonListarFuncionarios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButtonCFilme.setText("Cadastrar Filme");
        jButtonCFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCFilmeActionPerformed(evt);
            }
        });

        jButtonListarFilmes.setText("Listar Filmes");
        jButtonListarFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarFilmesActionPerformed(evt);
            }
        });

        jButtonCadastrarCliente.setText("Cadastrar Cliente");
        jButtonCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarClienteActionPerformed(evt);
            }
        });

        jButtonListarCLiente.setText("Listar Clientes");
        jButtonListarCLiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarCLienteActionPerformed(evt);
            }
        });

        jButtonCadastrarFuncionario.setText("Cadastrar  Funcionario");
        jButtonCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarFuncionarioActionPerformed(evt);
            }
        });

        jButtonListarFuncionarios.setText("Listar Funcionarios");
        jButtonListarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarFuncionariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelBemvindo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonListarFilmes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCFilme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCadastrarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonListarCLiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCadastrarFuncionario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonListarFuncionarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelBemvindo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCFilme)
                    .addComponent(jButtonCadastrarCliente)
                    .addComponent(jButtonCadastrarFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonListarFilmes)
                    .addComponent(jButtonListarCLiente)
                    .addComponent(jButtonListarFuncionarios))
                .addGap(0, 34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarClienteActionPerformed
        // TODO add your handling code here:
        CadastrarUsuario frame = new CadastrarUsuario(controladorU, u, false);
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_jButtonCadastrarClienteActionPerformed

    private void jButtonListarCLienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarCLienteActionPerformed
        // TODO add your handling code here:
        for(Usuario u: controladorU.getUsuariosCadastrados("usuario")){
            System.out.println(u.getNome() +" " + u.getCpf());
        }
        TodosUsuarios frame = new TodosUsuarios(controladorU, u, false);
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_jButtonListarCLienteActionPerformed

    private void jButtonCFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCFilmeActionPerformed
        try {
            // TODO add your handling code here:
            new CadastrarFilme(controladorF).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCFilmeActionPerformed

    private void jButtonCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarFuncionarioActionPerformed
        // TODO add your handling code here:
        CadastrarUsuario frame = new CadastrarUsuario(controladorU, u, true);
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_jButtonCadastrarFuncionarioActionPerformed

    private void jButtonListarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarFuncionariosActionPerformed
        // TODO add your handling code here:
        TodosFuncionarios frame = new TodosFuncionarios(controladorU, u);
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_jButtonListarFuncionariosActionPerformed

    private void jButtonListarFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarFilmesActionPerformed
        // TODO add your handling code here:
        TodosFilmes frame = null;
        try {
            frame = new TodosFilmes(controladorF, u);
        } catch (ParseException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_jButtonListarFilmesActionPerformed

    /**
     * @param args the command line arguments
     */
    private ControladorUsuarios controladorU;
    private ControladorFilmes controladorF;
    private Usuario u;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCFilme;
    private javax.swing.JButton jButtonCadastrarCliente;
    private javax.swing.JButton jButtonCadastrarFuncionario;
    private javax.swing.JButton jButtonListarCLiente;
    private javax.swing.JButton jButtonListarFilmes;
    private javax.swing.JButton jButtonListarFuncionarios;
    private javax.swing.JLabel jLabelBemvindo;
    // End of variables declaration//GEN-END:variables
}
