/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ControladorUsuarios;
import Modelo.TipoUsuario;
import Modelo.Usuario;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author JW
 */
public class TodosUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form TodosUsuarios
     */
    public TodosUsuarios(ControladorUsuarios controlador) {
        
        this.controladorU=controlador;
        initComponents();
        javax.swing.table.DefaultTableModel val = (javax.swing.table.DefaultTableModel) jTableUsuarios.getModel();
        ArrayList<Usuario> usuarios = controladorU.getUsuariosCadastrados("usuario");
        for(Usuario u : usuarios){
             val.addRow(new Object[]{u.getNome(), u.getCpf(), u.getTipoUsuario().toString(), u.getTelefone(), u.getNascimento(), u.getEndereco().getCep()});
        }
        //this.setSize(600, 600);
        this.jTableUsuarios.setSize(500, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuarios = new javax.swing.JTable();
        jButtonExcluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "Tipo Usuário", "Telefone", "Data Nascimento", "CEP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableUsuarios);

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButtonExcluir)
                .addGap(30, 30, 30)
                .addComponent(jButtonEditar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonEditar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        javax.swing.table.DefaultTableModel val = (javax.swing.table.DefaultTableModel) jTableUsuarios.getModel();
        int i = jTableUsuarios.getSelectedRow();
        if(i==-1){
            System.out.println("Erro");
            JOptionPane.showMessageDialog(null, "Favor selecionar um cliente!", "", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            try {
                controladorU.removeUsuario(val.getValueAt(i, 1).toString());
                JOptionPane.showMessageDialog(null, "Usuario excluido com sucesso", "", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                Logger.getLogger(TodosUsuarios.class.getName()).log(Level.SEVERE, null, ex);
            }
            val.removeRow(i);
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        int i = jTableUsuarios.getSelectedRow();
       if(i==-1){
            JOptionPane.showMessageDialog(null,"Favor selecionar um cliente!");
        }
        else{
            CadastrarUsuario frame = new CadastrarUsuario(controladorU);
            Usuario u = null;
            try {
                u = controladorU.buscaUsuario(jTableUsuarios.getValueAt(i, 1).toString());
            } catch (SQLException ex) {
                Logger.getLogger(TodosUsuarios.class.getName()).log(Level.SEVERE, null, ex);
            }
            frame.jTextFieldNome.setText(u.getNome());
            frame.jTextFieldBairro.setText(u.getEndereco().getBairro());
            frame.jTextFieldCEP.setText(u.getEndereco().getCep());
            frame.jTextFieldLogradouro.setText(u.getEndereco().getLogradouro());
            frame.jTextFieldNumero.setText(Integer.toString(u.getEndereco().getNumero()));
            frame.jTextFieldTelefone.setText(u.getTelefone());
            frame.jFormattedTextFieldCPF.setText(u.getCpf());
            System.out.println(u.getNascimento().toString());
            frame.jFormattedTextFielddata.setText(u.getNascimento().toString());
            if(u.getTipoUsuario()==TipoUsuario.CLIENTE)
                frame.jCheckBoxDependente.setSelected(false);
            else
                frame.jCheckBoxDependente.setSelected(true);
            frame.setVisible(true);
            frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
       }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    private ControladorUsuarios controladorU;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsuarios;
    // End of variables declaration//GEN-END:variables
}
